# build from debian by default
image: "alextee12/debian:0.5"

variables:
  _USER: "builduser"
  _PATH: /home/$_USER/$CI_PROJECT_NAME
  _PACKAGE_NAME: $CI_PROJECT_NAME-$CI_COMMIT_REF_NAME
  _DEBIAN_PACKAGE_NAME: $CI_PROJECT_NAME_$CI_COMMIT_REF_NAME

stages:
  - src_tar
  - build

build_src_tarball:
  stage: src_tar
  script:
    - mkdir $_PACKAGE_NAME
    - mv autogen.sh debian config.guess config.sub
      configure.ac CONTRIBUTING data Doxyfile inc INSTALL install-sh
      LICENSE Makefile.in README.md resources src $_PACKAGE_NAME/
    - tar -zcvf $_PACKAGE_NAME.tar.gz $_PACKAGE_NAME
  artifacts:
    paths:
    - ./$_PACKAGE_NAME.tar.gz
    expire_in: 1 week
  only:
    - tags
    - master

build_deb_64:
  stage: build
  script:
    - scripts/package-deb.sh
    - mv $_PATH/*.deb ./
  artifacts:
    paths:
    - ./*amd64.deb
    expire_in: 1 week
  only:
    - tags
    - master

build_pkg_64:
  image: "alextee12/arch-yaourt:0.3"
  stage: build
  script:
    - scripts/package-pkg.sh
    - cp $_PATH/*.pkg.tar.xz ./
  artifacts:
    paths:
    - ./*.pkg.tar.xz
    expire_in: 1 week
  only:
    - tags
    - master

build_rpm_64:
  image: "alextee12/fedora:0.3"
  stage: build
  script:
    - echo hello
    - ./autogen.sh
    - ./configure --enable-release --prefix=/usr
    - make -j8
  artifacts:
    paths:
    expire_in: 1 week
  only:
    - tags
    - master
