# build from debian by default
#image: "registry.zrythm.org/zrythm/zrythm/debian/latest:latest"
#image: "alextee12/debian-9"
image: "alextee12/arch-yaourt"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build_gnu_linux
  - build_other
  - package

basic_build_gcc_meson:
  stage: build_gnu_linux
  script:
    - meson _build -Denable_tests=true
    - ninja -C _build
    - .gitlab-ci/run-tests.sh
    - sudo meson install -C _build
  artifacts:
    reports:
      junit: "_build/${CI_JOB_NAME}-report.xml"
    paths:
      - "_build/config.h"
      - "_build/meson-logs"
      - "_build/${CI_JOB_NAME}-report.xml"

basic_build_clang_meson:
  stage: build_gnu_linux
  script:
    - CC=clang meson _build -Denable_tests=true
    - ninja -C _build
    - .gitlab-ci/run-tests.sh
    - sudo meson install -C _build
  artifacts:
    reports:
      junit: "_build/${CI_JOB_NAME}-report.xml"
    paths:
      - "_build/config.h"
      - "_build/meson-logs"
      - "_build/${CI_JOB_NAME}-report.xml"

# keep for a while then delete
basic_build_gcc_make:
  stage: build_gnu_linux
  script:
    - ./autogen.sh
    - ./configure
    - make -j14
    - sudo make install

package_win_64:
  stage: package
  image: "alextee12/arch-yaourt"
  script:
    - ./autogen.sh
    - x86_64-w64-mingw32-configure .
    - make -j14
  artifacts:
    paths:
      - build/win/Install_$CI_COMMIT_TAG.exe
    expire_in: 1 week
