image: "alextee12/arch-yaourt"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build_gnu_linux
  - test
  - package

basic_build_gcc_meson:
  stage: build_gnu_linux
  script:
    - meson _build
    - ninja -C _build
    - sudo meson install -C _build

basic_build_clang_meson:
  stage: build_gnu_linux
  script:
    - CC=clang meson _build
    - ninja -C _build
    - sudo meson install -C _build

test_gcc_meson:
  stage: test
  script:
    - meson _build -Denable_tests=true -Db_coverage=true
    - .gitlab-ci/run-tests.sh
    - ninja -C _build coverage-html
  artifacts:
    reports:
      junit: "_build/${CI_JOB_NAME}-report.xml"
    paths:
      - "_build/config.h"
      - "_build/meson-logs"
      - "_build/${CI_JOB_NAME}-report.xml"
      - "_build/${CI_JOB_NAME}-report.xml"
      - "_build/meson-logs/coveragereport/index.html"
  coverage: '/^lines: (\d+(?:\.\d+)?%)/'

package_win_64:
  stage: package
  image: "alextee12/arch-yaourt"
  script:
    - x86_64-w64-mingw32-meson _build
    - ninja -C _build && scripts/package_win.sh /usr/x86_64-w64-mingw32/ $CI_COMMIT_TAG . _win
  artifacts:
    paths:
      - build/win/Install_$CI_COMMIT_TAG.exe
    expire_in: 1 week
