# Official language image. Look for the different tagged releases at:
image: "debian:buster"

variables:
  _USER: "builduser"
  _PATH: /home/$_USER/$CI_PROJECT_NAME
  _ARCH_USER: "user"
  _ARCH_PATH: /home/$_ARCH_USER/$CI_PROJECT_NAME

stages:
  - src_tar
  - build

build_src_tarball:
  stage: src_tar
  script:
    - tar -zcvf sources.tar.gz autogen.sh config.guess config.sub
      configure.ac CONTRIBUTING data Doxyfile inc INSTALL install-sh
      LICENSE Makefile.in README.md resources src
  artifacts:
    paths:
    - ./*.tar.gz
    expire_in: 1 week
  only:
    - tags
    - master

build_deb_64:
  image: "debian:buster"
  stage: build
  script:
    - apt-get update -qq && apt-get install -y -qq libxml2-dev libgtk-3-dev
      libjack-dev liblilv-dev libsuil-dev libsmf-dev libsndfile1-dev libdazzle-1.0-dev
      lv2-dev
    - ./autogen.sh
    - ./configure
    - make -j14
  artifacts:
    paths:
    - PKGBUILD
    expire_in: 1 week
  only:
    - tags
    - master

build_pkg_64:
  image: heichblatt/archlinux-yaourt
  stage: build
  script:
    - yaourt -Sy --noconfirm gtk3 lv2 lilv-git suil-git jack libsndfile libsmf libdazzle
    - mkdir -p $_ARCH_PATH
    - mv * $_ARCH_PATH
    - pushd $_ARCH_PATH
    - makepkg
    - popd
    - sudo mv $_ARCH_PATH/*.pkg.tar.xz .
  artifacts:
    paths:
    - ./*.pkg.tar.xz
    expire_in: 1 week
  only:
    - tags
    - master
