# build from debian by default
#image: "registry.zrythm.org/zrythm/zrythm/debian/latest:latest"
#image: "alextee12/debian-9"
image: "alextee12/arch-yaourt"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build_gnu_linux
  - build_other
  - package

basic_build:
  stage: build_gnu_linux
  script:
    - ./autogen.sh
    - ./configure
    - sudo make -j14
    - sudo make install

package_win_64:
  stage: package
  image: "alextee12/arch-yaourt"
  script:
    - ./autogen.sh
    - x86_64-w64-mingw32-configure .
    - make -j14
  artifacts:
    paths:
      - build/win/Install_$CI_COMMIT_TAG.exe
    expire_in: 1 week
