# Copyright (C) 2019 Alexandros Theodotou <alex at zrythm dot org>
#
# This file is part of Zrythm
#
# Zrythm is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Zrythm is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Zrythm.  If not, see <https://www.gnu.org/licenses/>.


image: "alextee12/arch-yaourt"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build_gnu_linux
  - test
  - package

basic_build_gcc_meson:
  stage: build_gnu_linux
  script:
    - meson _build
    - ninja -C _build
    - sudo meson install -C _build

basic_build_clang_meson:
  stage: build_gnu_linux
  script:
    - CC=clang meson _build
    - ninja -C _build
    - sudo meson install -C _build

test_gcc_meson:
  stage: test
  script:
    - meson _build -Denable_tests=true -Db_coverage=true
    - .gitlab-ci/run-tests.sh
    - ninja -C _build coverage-html
  artifacts:
    reports:
      junit: "_build/${CI_JOB_NAME}-report.xml"
    paths:
      - "_build/config.h"
      - "_build/meson-logs"
      - "_build/${CI_JOB_NAME}-report.xml"
      - "_build/${CI_JOB_NAME}-report.xml"
      - "_build/meson-logs/coveragereport/index.html"
  coverage: '/^lines: (\d+(?:\.\d+)?%)/'
