# build from debian by default
#image: "registry.zrythm.org/zrythm/zrythm/debian/latest:latest"
image: "alextee12/debian9"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

test_build:
  stage: build
  script:
    - ./autogen.sh
    - ./configure
    - sudo make -j14
    - sudo make install
