# build from debian by default
image: "alextee12/debian:0.5"

variables:
  _USER: "builduser"
  _PATH: /home/$_USER/$CI_PROJECT_NAME
  _PACKAGE_NAME: $CI_PROJECT_NAME-$CI_COMMIT_REF_NAME
  _DEBIAN_VER: "0.1"

stages:
  - build

build_src_tarball:
  stage: build
  script:
    - PACKAGE_NAME=$_PACKAGE_NAME scripts/create-tarball.sh
  artifacts:
    paths:
    - ./$_PACKAGE_NAME.tar.gz
    expire_in: 4 weeks
  only:
    - tags
    - master

build_deb_64:
  stage: build
  script:
    - export PACKAGE_NAME="$CI_PROJECT_NAME"_"$_DEBIAN_VER"
    - sed -e "s/@BRANCH@/$CI_COMMIT_REF_NAME/" debian/changelog.in > debian/changelog && rm debian/changelog.in
    - scripts/create-tarball.sh
    - scripts/package-deb.sh
    - mv $_PATH/*.deb ./
  artifacts:
    paths:
    - ./zrythm_*amd64.deb
  only:
    - tags

build_deb_64_unstable:
  stage: build
  script:
    - export PACKAGE_NAME="$CI_PROJECT_NAME"_"$_DEBIAN_VER"
    - sed -e "s/@BRANCH@/$_DEBIAN_VER/" debian/changelog.in > debian/changelog && rm debian/changelog.in
    - scripts/create-tarball.sh
    - scripts/package-deb.sh
    - mv $_PATH/*.deb ./
  artifacts:
    paths:
    - ./zrythm_*amd64.deb
    expire_in: 4 weeks
  only:
    - master

build_pkg_64:
  image: "alextee12/arch-yaourt:0.4"
  stage: build
  script:
    - PACKAGE_NAME=$_PACKAGE_NAME scripts/create-tarball.sh
    - scripts/package-pkg.sh
    - cp $_PATH/*.pkg.tar.xz ./
  artifacts:
    paths:
    - ./*.pkg.tar.xz
    expire_in: 4 weeks
  only:
    - tags
    - master

build_rpm_64:
  image: "alextee12/fedora:0.3"
  stage: build
  script:
    - echo hello
    - ./autogen.sh
    - ./configure --enable-release --prefix=/usr
    - make -j8
  artifacts:
    paths:
    expire_in: 4 weeks
  only:
    - tags
    - master
