# build from debian by default
image: "alextee12/debian:0.4"

variables:
  _USER: "builduser"
  _PATH: /home/$_USER/$CI_PROJECT_NAME

stages:
  - src_tar
  - build

build_src_tarball:
  stage: src_tar
  script:
    - tar -zcvf sources.tar.gz autogen.sh config.guess config.sub
      configure.ac CONTRIBUTING data Doxyfile inc INSTALL install-sh
      LICENSE Makefile.in README.md resources src
  artifacts:
    paths:
    - ./*.tar.gz
    expire_in: 1 week
  only:
    - tags
    - master

build_deb_64:
  image: "alextee12/debian:0.4"
  stage: build
  script:
    - sudo apt-get install -y -qq libxml2-dev libgtk-3-dev
      libjack-dev liblilv-dev libsuil-dev libsmf-dev libsndfile1-dev autoconf
      lv2-dev libdazzle-1.0-dev
    - ./autogen.sh
    - ./configure --enable-release
    - make -j14
  artifacts:
    paths:
    - PKGBUILD
    expire_in: 1 week
  only:
    - tags
    - master

build_pkg_64:
  image: "alextee12/arch-yaourt:0.2"
  stage: build
  script:
    - yaourt -Sy --noconfirm gtk3 lv2 lilv suil jack libsndfile libsmf libdazzle
    - mkdir -p $_PATH
    - mv sources.tar.gz PKGBUILD $_PATH
    - pushd $_PATH
    - makepkg
    - popd
    - sudo mv $_PATH/*.pkg.tar.xz .
  artifacts:
    paths:
    - ./*.pkg.tar.xz
    expire_in: 1 week
  only:
    - tags
    - master

build_rpm_64:
  image: "alextee12/fedora:0.2"
  stage: build
  script:
    - echo hello
  artifacts:
    paths:
    - ./*.pkg.tar.xz
    expire_in: 1 week
  only:
    - tags
    - master
