# Copyright (C) 2020 Alexandros Theodotou <alex at zrythm dot org>
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.

language: c
os:
  - windows
  - osx
  - linux
dist: bionic

before_install:
- |-
  set -e
  case $TRAVIS_OS_NAME in
    windows)
      [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
      choco uninstall -y mingw
      choco upgrade --no-progress -y msys2
      export msys2='cmd //C RefreshEnv.cmd '
      export msys2+='& set MSYS=winsymlinks:nativestrict '
      export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
      export mingw64="$msys2 -mingw64 -full-path -here -c \$\* --"
      export msys2+=" -msys2 -c \$\* --"
      $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-toolchain mingw-w64-x86_64-gtk3 mingw-w64-x86_64-meson mingw-w64-x86_64-libsamplerate mingw-w64-x86_64-fftw mingw-w64-x86_64-ffmpeg mingw-w64-x86_64-libyaml mingw-w64-x86_64-libsndfile mingw-w64-x86_64-rubberband mingw-w64-x86_64-dlfcn mingw-w64-x86_64-SDL2 mingw-w64-x86_64-chromaprint guile libguile-devel
      ## Install more MSYS2 packages from https://packages.msys2.org/base here
      taskkill //IM gpg-agent.exe //F || true # https://travis-ci.community/t/4967
      export PATH=/C/tools/msys64/mingw64/bin:$PATH
      export MAKE=mingw32-make  # so that Autotools can find it
      ;;
    osx)
      brew update
      # use || true because it returns 1
      brew install fftw meson libsamplerate sdl2 chromaprint libgtop lilv librsvg gtk+3 guile || true
      brew link --overwrite python
      ;;
    linux)
      sudo apt-get install -y libgtk-3-dev libjack-dev libsndfile1-dev ninja-build gettext sed help2man python3-sphinx ladspa-sdk libfftw3-dev libasound2-dev libavcodec-dev libavutil-dev libavformat-dev libchromaprint-dev libsamplerate0-dev libyaml-dev librubberband-dev python3 xdg-utils git lcov guile-2.2-dev
      git clone https://github.com/mesonbuild/meson /tmp/meson
      pip install --user gcovr cpp-coveralls
      ;;
  esac

before_cache:
- |-
  set -e
  case $TRAVIS_OS_NAME in
    windows)
      # https://unix.stackexchange.com/a/137322/107554
      $msys2 pacman --sync --clean --noconfirm
      ;;
  esac

cache:
  directories:
  - $HOME/AppData/Local/Temp/chocolatey
  - /C/tools/msys64

script:
- |-
  set -e
  case $TRAVIS_OS_NAME in
    osx)
      meson build -Denable_sdl=true -Denable_rtaudio=true -Denable_rtmidi=true -Denable_tests=true -Denable_jack=false
      ninja -C build
      ninja -C build test
      sudo ninja -C build install
      ;;
    windows)
      # hack to enable tests
      $mingw64 sed -i -e '27s/false/true/' meson_options.txt
      # hack to enable sdl
      $mingw64 sed -i -e '63s/false/true/' meson_options.txt
      # hack to disable jack
      $mingw64 sed -i -e '75s/true/false/' meson_options.txt
      # hack to disable guile
      $mingw64 sed -i -e '131s/true/false/' meson_options.txt
      $mingw64 meson build
      $mingw64 ninja -C build
      $mingw64 ninja -C build test
      $mingw64 ninja -C build install
      ;;
    linux)
      /tmp/meson/meson.py build -Denable_tests=true -Db_coverage=true
      ninja -C build
      ninja -C build test
      ninja -C build coverage-text
      coveralls -e ext -e tests -e subprojects -e doc -e build/resources -b build --gcov-options '\-lp'
      sudo ninja -C build install
      ;;
  esac
